/**
 * lexicon.js
 * Centraliza solo verbos de interfaz. Las entidades son soberanía del Core.
 */

const LEXICON = {
    es: {
        action_sync: "SINCRONIZAR",
        action_back: "VOLVER",
        action_generate: "NUEVO",
        action_save: "GUARDAR",
        action_edit: "EDITAR",
        action_preview: "VISTA PREVIA",
        action_export: "EXPORTAR",
        action_refresh: "ACTUALIZAR",
        action_new_event: "NUEVO_EVENTO",
        action_reschedule: "REPROGRAMAR",
        action_migrate_silo: "MIGRAR",
        action_copy_id: "COPIAR_ID",
        action_delete: "ELIMINAR",
        action_link_reality: "BUSCAR",
        action_add_item: "AÑADIR_REGISTRO",
        action_execute: "EJECUTAR_FLUJO",
        action_activate: "ACTIVAR_ESPACIO",
        action_generate_ws: "MATERIALIZAR_WORKSPACE",
        action_delete_ws: "BORRAR_WORKSPACE",
        action_disconnect: "DESCONECTAR",
        action_authorize: "AUTORIZAR_Y_VINCULAR",
        action_finish: "FINALIZAR",
        action_cancel: "CANCELAR",
        status_draft: "BORRADOR",
        status_live: "PUBLICADO",
        status_unnamed: "SIN_NOMBRE",
        status_loading: "CARGANDO...",
        status_syncing: "GUARDANDO...",
        status_stable: "ESTABLE",
        status_empty_list: "LISTA_VACÍA",
        status_executing: "EJECUTANDO...",
        status_thinking: "DESCUBRIENDO_CONTEXTO...",
        status_offline: "ESTADO_DESCONECTADO",
        status_agent_ready: "AGENTE_INICIALIZADO",
        status_waiting_input: "ESPERANDO_INTENCIÓN...",
        status_error: "ERROR_OPERATIVO",
        status_materializing: "MATERIALIZANDO...",
        status_establishing: "ESTABLECIENDO_TÚNEL...",
        status_inactive: "INACTIVO",
        status_encrypted: "TÚNEL_CIFRADO",
        status_active: "ACTIVO",
        status_ready_pair: "LISTO_PARA_VINCULAR",
        status_encrypting: "CIFRANDO_CREDENCIALES...",
        status_vault_ok: "CREDENCIAL_ACEPTADA_POR_BÓVEDA",
        ui_layers: "ESTRUCTURA_CAPAS",
        ui_properties: "INSPECTOR_DNA",
        ui_canvas: "VIEWPORT_DISEÑO",
        ui_sources: "FUENTES_ENTRADA",
        ui_targets: "DESTINOS_SALIDA",
        ui_transformation: "FLUJO_LÓGICA",
        ui_simulator: "SIMULADOR_CÁLCULO",
        ui_timeline: "LÍNEA_TIEMPO",
        ui_calendar: "GRILLA_TEMPORAL",
        ui_controls: "CONTROLES_MOTOR",
        ui_theme: "TEMA",
        ui_theme_selection: "SELECCIÓN_ESTÉTICA",
        ui_style_engine: "MOTOR_ESTILO",
        ui_new_operation: "NUEVA_OPERACIÓN",
        ui_inspector: "INSPECTOR",
        ui_toolbar: "HERRAMIENTAS",
        ui_project_id: "ID_PROYECTO",
        ui_multi_view: "VISTA_MÚLTIPLE",
        ui_silo_view: "VISTA_SILO",
        ui_binary_operations: "OPERACIONES_BINARIAS",
        ui_silo_control: "CONTROL_SILOS",
        ui_session: "SESIÓN",
        ui_group: "GRUPO",
        ui_list: "LISTA",
        ui_schema_projection: "PROYECCIÓN_ESQUEMA",
        ui_column_potency: "I. ESTRUCTURA",
        ui_column_agency: "II. LÓGICA",
        ui_column_manifestation: "III. RESULTADOS",
        ui_agent_chat: "CHAT_OPERATIVO",
        ui_agent_config: "CONFIGURACIÓN_IA",
        ui_role_ai: "INTELIGENCIA",
        ui_role_operator: "OPERADOR",
        ui_role_system: "SISTEMA",
        ui_maintenance_mode: "MODO_MANTENIMIENTO",
        ui_config_required: "CONFIGURACIÓN_REQUERIDA",
        ui_maintenance_desc: "Ajusta parámetros cognitivos o cambia de modelo.",
        ui_config_required_desc: "Configura llaves locales para despertar al agente.",
        ui_keys_config: "LLAVES_SOBERANAS",
        ui_data_sovereignty: "SOBERANÍA_TOTAL",
        ui_data_sovereignty_desc: "Tus llaves permanecen encriptadas localmente.",
        ui_input_placeholder: "Define intención (ej: 'Busca balances en Drive')...",
        ui_system_id: "INDRA_CORE",
        ui_system_awakening: "DESPERTAR_SISTEMA",
        ui_identity_config: "01 // ETIQUETA_LOCAL",
        ui_identity_desc: "Apodo técnico para este vínculo en este navegador.",
        ui_identity_placeholder: "EJ: PRODUCCION_ESTUDIO",
        ui_resonance_config: "02 // RESONANCIA_BASE",
        ui_resonance_desc: "URL del despliegue de Google Apps Script.",
        ui_secret_config: "03 // LLAVE_SOBERANA",
        ui_secret_desc: "Credencial AES de acceso al núcleo sistémico.",
        ui_connect_action: "INICIAR_VÍNCULO_CORE",
        ui_infra_manager: "GESTOR_INFRAESTRUCTURA",
        ui_vault_encryption: "BÓVEDA_CIFRADO: AES_256",
        ui_exit_infra: "SALIR_INFRA",
        ui_overview: "VISTA_GENERAL",
        ui_active_services: "SERVICIOS_ACTIVOS",
        ui_pending_pairing: "VINCULACIONES_PENDIENTES",
        ui_security_log: "REGISTRO_SEGURIDAD",
        ui_providers: "PROVEEDORES_DISPONIBLES",
        ui_pairing: "VINCULACIÓN",
        ui_pairing_desc: "Ingrese credenciales para autorizar el túnel.",
        ui_provider_secret: "SECRETO_PROVEEDOR (API_KEY)",
        ui_vault_notice: "Las llaves son cifradas en reposo dentro del core.",
        ui_hud_active_workspaces: "WORKSPACES_ACTIVOS",
        ui_hud_ws_identity: "IDENTIDAD_WS",
        ui_hud_pins: "PINS",
        ui_id_core: "NÚCLEO",
        ui_hud_system_log: "BITÁCORA_SISTEMA",
        hold_to_delete: "MANTENER_PARA_BORRAR",
        hud_service_fabric: "TEJIDO_DE_SERVICIOS",
        action_manage_services: "GESTOR_INFRA",
        hud_nexus_control: "CENTRO_NEXUS",
        action_seed_potency: "CREAR_OBJETO",
        action_ignite_agency: "NUEVO_MOTOR",
        action_harvest_manifestation: "VER_RESULTADO",
        action_harvest: "ABRIR",
        ui_empty_potency: "SIN OBJETOS",
        ui_empty_potency_desc: "No hay estructuras de datos o esquemas aquí.",
        ui_empty_agency: "SIN PROCESOS",
        ui_empty_agency_desc: "Aquí aparecerán tus puentes y flujos lógicos.",
        ui_empty_manifestation: "SIN RESULTADOS",
        ui_empty_manifestation_desc: "Los documentos y logros se listarán aquí.",
        ui_bridge: "PUENTE",
        ui_workflow: "FLUJO",
        ui_operational_pulse: "PULSAR_OPERACIÓN",
        ui_focus_engine: "ENFOCAR_MOTOR",
        ui_ready_for_exec: "// LISTO_PARA_EJECUCIÓN",

        // Entidades (Motores Reales)
        DATA_SCHEMA: "TABLA DE DATOS",
        LOGIC_BRIDGE: "UNIÓN DE DATOS (BRIDGE)",
        WORKFLOW_DESIGNER: "FLUJO DE TRABAJO",
        DOCUMENT_DESIGNER: "DOCUMENTO (PÁGINA)",
        VIDEO_PROJECT: "PROYECTO DE VIDEO",
        AEE_RUNNER: "FORMULARIO / DASHBOARD",
        CALENDAR_HIVE: "AGENDA / CALENDARIO",
        FOLDER: "CARPETA"
    },
    en: {
        action_sync: "SYNC",
        action_back: "BACK",
        action_generate: "NEW",
        action_save: "SAVE",
        action_edit: "EDIT",
        action_preview: "PREVIEW",
        action_export: "EXPORT",
        action_refresh: "REFRESH",
        action_new_event: "NEW_EVENT",
        action_reschedule: "RESCHEDULE",
        action_migrate_silo: "MIGRATE",
        action_copy_id: "COPY_ID",
        action_delete: "DELETE",
        action_link_reality: "SEARCH",
        action_add_item: "ADD_RECORD",
        action_execute: "EXECUTE_FLOW",
        action_activate: "ACTIVATE_SPACE",
        action_generate_ws: "MATERIALIZE_WORKSPACE",
        action_delete_ws: "DELETE_WORKSPACE",
        action_disconnect: "DISCONNECT",
        action_authorize: "AUTHORIZE_AND_PAIR",
        action_finish: "FINISH",
        action_cancel: "CANCEL",
        status_draft: "DRAFT",
        status_live: "LIVE",
        status_unnamed: "UNNAMED",
        status_loading: "LOADING...",
        status_syncing: "SAVING...",
        status_stable: "STABLE",
        status_empty_list: "EMPTY_LIST",
        status_executing: "EXECUTING...",
        status_thinking: "DISCOVERING_CONTEXT...",
        status_offline: "OFFLINE_STATE",
        status_agent_ready: "AGENT_INITIALIZED",
        status_waiting_input: "WAITING_INTENT...",
        status_error: "OPERATIONAL_ERROR",
        status_materializing: "MATERIALIZING...",
        status_establishing: "ESTABLISHING_TUNNEL...",
        status_inactive: "INACTIVE",
        status_encrypted: "ENCRYPTED_TUNNEL",
        status_active: "ACTIVE",
        status_ready_pair: "READY_TO_PAIR",
        status_encrypting: "ENCRYPTING_CREDENTIALS...",
        status_vault_ok: "CREDENTIAL_ACCEPTED_BY_VAULT",
        ui_layers: "LAYERS_STRUCTURE",
        ui_properties: "DNA_INSPECTOR",
        ui_canvas: "DESIGN_VIEWPORT",
        ui_sources: "INPUT_SOURCES",
        ui_targets: "OUTPUT_TARGETS",
        ui_transformation: "LOGIC_FLOW",
        ui_simulator: "CALC_SIMULATOR",
        ui_timeline: "TIMELINE",
        ui_calendar: "TEMPORAL_GRID",
        ui_controls: "ENGINE_CONTROLS",
        ui_theme: "THEME",
        ui_theme_selection: "THEME_SELECTION",
        ui_style_engine: "STYLE_ENGINE",
        ui_new_operation: "NEW_OPERATION",
        ui_inspector: "INSPECTOR",
        ui_toolbar: "TOOLBAR",
        ui_project_id: "PROJECT_ID",
        ui_multi_view: "MULTI_VIEW",
        ui_silo_view: "SILO_VIEW",
        ui_binary_operations: "BINARY_OPERATIONS",
        ui_silo_control: "SILO_CONTROL",
        ui_session: "SESSION",
        ui_group: "GROUP",
        ui_list: "LIST",
        ui_schema_projection: "SCHEMA_PROJECTION",
        ui_column_potency: "I. STRUCTURE",
        ui_column_agency: "II. LOGIC",
        ui_column_manifestation: "III. RESULTS",
        ui_agent_chat: "OPERATIONAL_CHAT",
        ui_agent_config: "AI_CONFIGURATION",
        ui_role_ai: "INTELLIGENCE",
        ui_role_operator: "OPERATOR",
        ui_role_system: "SYSTEM",
        ui_maintenance_mode: "MAINTENANCE_MODE",
        ui_config_required: "CONFIGURATION_REQUIRED",
        ui_maintenance_desc: "Adjust cognitive parameters or change models.",
        ui_config_required_desc: "Configure local keys to wake the agent.",
        ui_keys_config: "SOVEREIGN_KEYS",
        ui_data_sovereignty: "TOTAL_SOVEREIGNTY",
        ui_data_sovereignty_desc: "Your keys remain encrypted locally.",
        ui_input_placeholder: "Define intent (e.g., 'Find balances in Drive')...",
        ui_system_id: "INDRA_CORE",
        ui_system_awakening: "SYSTEM_AWAKENING",
        ui_identity_config: "01 // IDENTITY",
        ui_identity_desc: "Technical name for this instance in local memory.",
        ui_identity_placeholder: "PRIMARY_INTERFACE_ID",
        ui_resonance_config: "02 // BASE_RESONANCE",
        ui_resonance_desc: "URL of the Google Apps Script deployment.",
        ui_secret_config: "03 // SOVEREIGN_KEY",
        ui_secret_desc: "AES credential for access to the systemic core.",
        ui_connect_action: "INITIATE_CORE_LINK",
        ui_infra_manager: "INFRA_MANAGER",
        ui_vault_encryption: "VAULT_ENCRYPTION: AES_256",
        ui_exit_infra: "EXIT_INFRA",
        ui_overview: "OVERVIEW",
        ui_active_services: "ACTIVE_SERVICES",
        ui_pending_pairing: "PENDING_PAIRING",
        ui_security_log: "SECURITY_LOG",
        ui_providers: "AVAILABLE_PROVIDERS",
        ui_pairing: "PAIRING",
        ui_pairing_desc: "Enter credentials to authorize the tunnel.",
        ui_provider_secret: "PROVIDER_SECRET (API_KEY)",
        ui_vault_notice: "Keys are encrypted at rest within the core.",
        ui_hud_active_workspaces: "ACTIVE_WORKSPACES",
        ui_hud_ws_identity: "WS_IDENTITY",
        ui_hud_pins: "PINS",
        ui_id_core: "CORE",
        ui_hud_system_log: "SYSTEM_LOG",
        hold_to_delete: "HOLD_TO_DELETE",
        hud_service_fabric: "SERVICE_FABRIC",
        action_manage_services: "MANAGE_INFRA",
        hud_nexus_control: "NEXUS_CONTROL",
        action_seed_potency: "SEED_POTENCY",
        action_ignite_agency: "IGNITE_AGENCY",
        action_harvest_manifestation: "HARVEST_ACHIEVEMENT",
        ui_operational_pulse: "OPERATIONAL_PULSE",
        ui_focus_engine: "FOCUS_ENGINE",
        ui_ready_for_exec: "// READY_FOR_EXEC",

        // Entities (Engines)
        DATA_SCHEMA: "DATA TABLE",
        LOGIC_BRIDGE: "DATA LINK (BRIDGE)",
        WORKFLOW_DESIGNER: "STEP FLOW",
        DOCUMENT_DESIGNER: "DOCUMENT (PAGE)",
        VIDEO_PROJECT: "VIDEO PROJECT",
        AEE_RUNNER: "FORM / DASHBOARD",
        CALENDAR_HIVE: "AGENDA / CALENDAR",
        FOLDER: "FOLDER"
    }
};

export const useLexicon = (lang = 'es') => {
    return (key) => {
        if (!key) return '';
        return LEXICON[lang]?.[key] || key.toUpperCase();
    };
};
