graph TD
    Reality[Reality.jsx] --> NodeEntity[NodeEntity.jsx]
    Reality --> useRealityWiring[useRealityWiring.js]
    Reality --> useRealityNavigation[useRealityNavigation.js]
    Reality --> SearchPort[SearchPort.jsx]
    
    NodeEntity --> Amnesia[Amnesia.js]
    useRealityWiring --> Amnesia
    useRealityNavigation --> Amnesia
    
    Amnesia --> CosmosSlice[CosmosSlice.js]
    Amnesia --> TopologySlice[TopologySlice.js]
    Amnesia --> SessionSlice[SessionSlice.js]
    
    SyncOrchestrator[SyncOrchestrator.js] --> PersistenceAgent[PersistenceAgent.js]
    PersistenceAgent --> DriveAdapter[DriveAdapter]
    
    CosmosSlice --> SyncOrchestrator
    TopologySlice --> SyncOrchestrator
    
    Neutron[Neutron.js] --> OrbitalCore[Orbital Core]
    Discovery[Discovery.js] --> Neutron
    Resolver[Resolver.js] --> DriveAdapter
